@startuml
'https://plantuml.com/class-diagram

Employee o-r- Role
Student o-r- Role
Department "*" *-d- "*" Subject: owns
Subject "*" -- "1" Course: is taught by
Student "*" -l- "*" Course : participates
Employee "*" -d- "*" Course : manages
Student "*" -- "0..1" Evaluation : do
Employee "*" -r- "0..1" Evaluation : applies
Employee .l. Department : member of
User <|-u- Employee : is a
User <|-- Student : is a

class Department {
+code: String
+name: String
+active: Boolean
}

class Course {
-code: String
-name: String
-active: Boolean
-startDate: Date
-endDate:Date
}

class Subject {
+description: String
+acronym: String
}

class Evaluation {
+description: String
+grade: Number
+date: DateTime
}

class Student {
-name: String
-registrationNumber: String
+role: Role.STUDENT
+enrollCourse()
+cancelCourseParticipation()
+getGradesByCourse()
+getCoursesEnrolled()
}

class Employee {
+roles: Role[]
+departments: Department[]
+registerStudentEvaluation()
+createCourse()
+deactivateCourse()
+createStudent()
+deactivateStudent()
+getCoursesByDepartment()
+getCoursesGradeByStudent()
}

class User {
-name: String
-registrationNumber: String
-username: String
-password: String
+changePassword()
+resetPassword()
}

enum Role {
DEPARTMENT_ADMIN
DEPARTMENT_OFFICER
STUDENT
TEACHER
}

@enduml